<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.jenkins-ci.plugins</groupId>
    <artifactId>plugin</artifactId>
    <version>5.7</version>
    <relativePath />
  </parent>

  <groupId>io.jenkins.plugins</groupId>
  <artifactId>hashicorp-nomad-plugin</artifactId>
  <version>${revision}${changelist}</version>
  <packaging>hpi</packaging>

  <name>HashiCorp Nomad Plugin</name>
  <description>Provision ephemeral Jenkins agents as Nomad jobs.</description>
  <url>https://github.com/dcanadillas/jenkins-hashicorp-nomad-plugin</url>

  <licenses>
    <license>
      <name>MIT License</name>
      <url>https://opensource.org/license/mit/</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <properties>
    <revision>0.1.0</revision>
    <changelist></changelist>
    <jenkins.baseline>2.479</jenkins.baseline>
    <jenkins.version>${jenkins.baseline}.3</jenkins.version>
    <gitHubRepo>dcanadillas/jenkins-hashicorp-nomad-plugin</gitHubRepo>
    <maven.compiler.release>17</maven.compiler.release>
    <spotbugs.skip>true</spotbugs.skip>
  </properties>

  <repositories>
    <repository>
      <id>repo.jenkins-ci.org</id>
      <url>https://repo.jenkins-ci.org/public/</url>
    </repository>
  </repositories>

  <pluginRepositories>
    <pluginRepository>
      <id>repo.jenkins-ci.org</id>
      <url>https://repo.jenkins-ci.org/public/</url>
    </pluginRepository>
  </pluginRepositories>

  <dependencies>
    <dependency>
      <groupId>org.jenkins-ci.plugins</groupId>
      <artifactId>credentials</artifactId>
      <version>1408.va_622a_b_f5b_1b_1</version>
    </dependency>
    <dependency>
      <groupId>org.jenkins-ci.plugins</groupId>
      <artifactId>plain-credentials</artifactId>
      <version>199.v9f8e1f741799</version>
    </dependency>
    <dependency>
      <groupId>org.jenkins-ci.plugins.workflow</groupId>
      <artifactId>workflow-step-api</artifactId>
      <version>700.v6e45cb_a_5a_a_21</version>
    </dependency>
    <dependency>
      <groupId>org.jenkinsci.plugins</groupId>
      <artifactId>pipeline-model-definition</artifactId>
      <version>2.2114.v2654ca_721309</version>
    </dependency>
    <dependency>
      <groupId>org.jenkins-ci.main</groupId>
      <artifactId>jenkins-test-harness</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <profiles>
    <profile>
      <id>java25-compatible-build</id>
      <activation>
        <jdk>[25,)</jdk>
      </activation>
      <properties>
        <license.disableCheck>true</license.disableCheck>
      </properties>
    </profile>
  </profiles>
</project>
