pipeline {
  agent none

  stages {
    stage('Nomad Pipeline Examples') {
      steps {
        echo 'Use one of the dedicated Nomad examples in this folder:'
        echo '- examples/Jenkinsfile.scripted.nomad'
        echo '- examples/Jenkinsfile.declarative.nomad'
      }
    }
  }
}
